project:
  type: website

website:
  page-navigation: true
  title: "BIOSTAT 725 - Spring 2025"
  description: "Homepage for BIOSTAT 725 - Bayesian Health Data Science at Duke University, Spring 2025"
  site-url: https://biostat725-sp25.netlify.app

  repo-url: https://github.com/biostat725-sp25/website
  repo-actions: [issue]
  
  page-footer:
    background: "#497E99"
    left: |
      &copy; Copyright 2025, Samuel Berchuck
    right: |
      This site is built with [Quarto](https://quarto.org/)

  sidebar:
    background: "#407E99"
    logo: "images/logo.png"
    align: center
    tools: 
      - icon: github
        href: https://github.com/biostat725-sp25
        text: "GitHub organization"
      - icon: code-square
        href: https://cmgr.oit.duke.edu/containers
        text: "RStudio Containers"
      - icon: chat-dots-fill
        href: https://edstem.org/us/courses/68995/discussion/
      - icon: check-square-fill
        menu:
          - text: Canvas
            url: https://canvas.duke.edu/courses/53305
          - text: Gradescope
            url: https://www.gradescope.com/courses/903622
    style: "docked"
    search: true
    collapse-level: 1
    contents: 
      - href: overview.qmd
        text: Overview
      - href: syllabus.qmd
        text: Syllabus
      - href: support.qmd
        text: Support
      - href: index.qmd
        text: Schedule 
      - href: links.qmd
        text: Useful links
      - section: Computing
        contents: 
        - href: computing-access.qmd
          text: Access
        - href: computing-troubleshooting.qmd
          text: Troubleshooting
        - href: computing-r-resources.qmd
          text: R resources
      - section: Homework
        contents:
        - href: hw/hw-00.qmd
          text: HW 00
        - href: hw/hw-01.qmd
          text: HW 01
        - href: hw/hw-02.qmd
          text: HW 02
        - href: hw/hw-03.qmd
          text: HW 03
        - href: hw/hw-04.qmd
          text: HW 04
        - href: hw/hw-05.qmd
          text: HW 05


format:
  html:
    theme:
      light: [cosmo, theme.scss]
    mainfont: "Open Sans"
    code-copy: true
    code-overflow: wrap
    toc: true

execute:
  freeze: auto

editor: visual    
    



